apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: gcp-pubsub-source
spec:
  vertices:
    - name: in
      scale:
        min: 1
      source:
        udsource:
          container:
            image: "quay.io/numaio/numaflow-go/gcloud-pubsub-source:latest"
            env:
              - name: PROJECT_ID
                value: "my-project-1500816644689"
              - name: TOPIC_ID
                value: "numaflow-topic"
              - name: SUBSCRIPTION_ID
                value: "numaflowtest"
              - name: PUBSUB_EMULATOR_HOST
                value: "" # For production keep it blank string
              - name: MAX_EXTENSION_PERIOD  #specifies the maximum period for which the deadline for message acknowledgment may be extended 30s ,30m
                value: "240s"

              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /var/secrets/google/key.json
            volumeMounts:
              - name: google-cloud-key
                mountPath: /var/secrets/google
      volumes:
        - name: google-cloud-key
          secret:
            secretName: google-cloud-key
    - name: redis-sink
      sink:
        udsink:
          container:
            image: "quay.io/numaio/numaflow-sink/redis-e2e-test-sink:v0.5.0"
  edges:
    - from: in
      to: redis-sink
